# Generated by Django 2.2.1 on 2021-06-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your Name ')),
                ('mobile', models.CharField(max_length=15, verbose_name='Your Mobile ')),
                ('email', models.EmailField(max_length=75, verbose_name='Your Email ')),
                ('doctor', models.CharField(choices=[('Dr. Rohit chabra', 'Dr. Rohit chabra'), ('Dr. Abbas Shahid', 'Dr. Abbas Shahid'), ('Dr. Abdul Malik', 'Dr. Abdul Malik'), ('Dr. Achraya Dilip', 'Dr. Achraya Dilip'), ('Dr. Achraya Dinesh', 'Dr. Achraya Dinesh'), ('Dr. Admane Neelima', 'Dr. Admane Neelima'), ('Dr. Dhanuka Sanjay', 'Dr. Dhanuka Sanjay'), ('Dr. Dhand Hemlata', 'Dr. Dhand Hemlata')], default='doctor', max_length=16)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
