# Generated by Django 2.2.19 on 2021-06-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='doctor',
            field=models.CharField(choices=[('Dr. Rohit chabra', 'Dr. Rohit chabra'), ('Dr. Abbas Shahid', 'Dr. Abbas Shahid'), ('Dr. Abdul Malik', 'Dr. Abdul Malik'), ('Dr. Achraya Dilip', 'Dr. Achraya Dilip'), ('Dr. Achraya Dinesh', 'Dr. Achraya Dinesh'), ('Dr. Admane Neelima', 'Dr. Admane Neelima'), ('Dr. Dhanuka Sanjay', 'Dr. Dhanuka Sanjay'), ('Dr. Dhand Hemlata', 'Dr. Dhand Hemlata')], default='doctor', max_length=50),
        ),
    ]
