# Generated by Django 2.2.19 on 2021-06-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210627_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='doctor',
            field=models.CharField(choices=[('dr.chabra', 'Dr. Rohit chabra'), ('dr.Shahid', 'Dr. Abbas Shahid'), ('dr.Malik', 'Dr. Abdul Malik'), ('dr.Dilip', 'Dr. Achraya Dilip'), ('dr.Dinesh', 'Dr. Achraya Dinesh'), ('dr.Neelima', 'Dr. Admane Neelima'), ('dr.Sanjay', 'Dr. Dhanuka Sanjay'), ('dr.Hemlata', 'Dr. Dhand Hemlata')], default='doctor', max_length=50),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='time',
            field=models.CharField(choices=[('morning', 'MORNING'), ('evening', 'EVENING')], default='time', max_length=50),
        ),
    ]
